function mail2_2( user,...
                  subject,...
                  message,...
                  attachment)% exclist
% by Tobias Bader 2022-04-06
% new version which uses powershell and dummy.d@lw-online to send messages
% Adapted by Michael Mohr 2025-06-16
M1 = strjoin(message,'<br />'); % changed from \n to HTML version (powershell)
%M2 = strjoin(message,' | ');

for i = 1:size(user,2)
   
    argument = strcat({'powershell -command "Send-MailMessage -BodyAsHtml -From '}, {'dummy.d@lw-online.de'},...
                      {' -Subject '},{''''},strcat(string(datetime(now,'ConvertFrom','datenum')),{' '},subject),{''''},...
                      {' -To '},{''''},user(i),{''''},...
                      {' -Body '},{''''}, string(M1),{''''},...
                      {' -SmtpServer Mail.lw-online.de'},...
                      {' -Attachments "'}, attachment, {'"'} ,'"');
    system(char(join(argument)));     
         
end
% documentation
% [~, existinglist]  = xlsread( exclist,'mails_cal' );
% xlswrite( exclist,...
%           cellstr(strcat( string(datetime(now,'ConvertFrom','datenum')),...
%           '_', strjoin(user,'_'), '_', subject, '_', M2)),...
%           'mails_cal',strcat('A',num2str(size(existinglist,1)+1)) )
end


