% ========================= AutoQ4MS HEADER START =========================
% Copyright © 2026 Zweckverband Landeswasserversorgung
% Author   : Linus Straehle
% Project  : AutoQ4MS
% License  : % License: GNU General Public License v3.0 (GPL-3.0) or later.
%          See the LICENSE file or https://www.gnu.org/licenses/gpl-3.0.html for details.
% ========================== AutoQ4MS HEADER END ==========================

function WarningPlusDb(string, Parameters, Warning_type)
%WARNINGPLUSDB  Issue a MATLAB warning and additionally log it to the database.
%
%   WarningPlusDb(msg, Parameters, Warning_type)
%   Emits a MATLAB warning and writes the same warning information into the
%   database table 'Warnings' via an autogenerated SQL file.
%
%   Inputs:
%     string        - Warning message text
%     Parameters    - Project parameters struct (database config + paths)
%     Warning_type  - Classification/category of the warning (string/char)
%

    warning(string);

    Warnings.String       = string;
    Warnings.datetime     = datetime('now');
    Warnings.Warning_type = Warning_type;

    filepath = newsqlfile(Parameters);

    fileID = fopen(filepath, 'w');
    fprintf(fileID, '%s\n', createSQLInsertCommand(Parameters, 'Warnings', Warnings));
    fclose(fileID);

    runsqlfile(filepath, Parameters);
end
