function WarningPlusDb(string, Parameters, Warning_type)
%WARNINGPLUSDB  Issue a MATLAB warning and additionally log it to the database.
%
%   WarningPlusDb(msg, Parameters, Warning_type)
%   Emits a MATLAB warning and writes the same warning information into the
%   database table 'Warnings' via an autogenerated SQL file.
%
%   Inputs:
%     string        - Warning message text
%     Parameters    - Project parameters struct (database config + paths)
%     Warning_type  - Classification/category of the warning (string/char)
%

    warning(string);

    Warnings.String       = string;
    Warnings.datetime     = datetime('now');
    Warnings.Warning_type = Warning_type;

    filepath = newsqlfile(Parameters);

    fileID = fopen(filepath, 'w');
    fprintf(fileID, '%s\n', createSQLInsertCommand(Parameters, 'Warnings', Warnings));
    fclose(fileID);

    runsqlfile(filepath, Parameters);
end
